void reset_to_98(int *);
void swap_int(int *, int *);
int _strlen(char *);
void _putchar(char);
void _puts(char *);
void print_rev(char *);
void rev_string(char *);
void puts2(char *str);
void puts_half(char *str);
void print_array(int *a, int n);
